### ISSUE TITLE
Add support for new VS Code version 1.76.0

### ISSUE THREAD

**Issue by PrabakaranSK** [ascpixi/vscode-path-go-to-definition#1]
Hi,

This extension is found to be not supported in VS Code version 1.76.0. 

While trying to install, got an error saying that:
Can't install 'ascpix.path-go-to-definition' extension because it is not compatible with the current version of Visual Studio Code (version 1.76.0).

_VS Code version details:_
Version: 1.76.0 (system setup)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:22:44.506Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

**Comment by ascpixi** [comment]
The current version of VSCode is 1.95.3 - try updating your install to at least 1.90.x.

**Comment by PrabakaranSK** [comment]
Hi, thanks for the reply.  My client system has IT restrictions hence can't update it to latest version.  I have upgraded to (max allowed) 1.89.1 version today but still unsupported.  Is it possible to make this plugin (backward compatible) to work with this version please?  This extension is very useful for C4 DSL files to navigate between other included files.  Unfortunately there are no other equivalent plugins out there, hence please see if this is possible.

**Comment by ascpixi** [comment]
I feel like the best course of action here is for you to fork the extension and change `engines` to be `^1.89.0` in `package.json`.

https://github.com/ascpixi/vscode-path-go-to-definition/blob/e746df2b39a058aa1172e0fb72bb2b1ad7769dfb/package.json#L11-L13

You can then run `npx vsce package` (make sure you do have `vsce` installed by doing `npm install -g @vscode/vsce`). That'll create a VSIX file you can deploy on your clients' machines (or you can even create your own version of the package - it's MIT licensed, so please feel free to do so!). I can't really reliably test if the extension would work under older versions - it _should_, but I don't think I have the time to properly test it.
